export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-family)"],
      },
      colors: {
        white: {
          DEFAULT: "var(--color-white)",
          2: "var(--color-white-2)",
          3: "var(--color-white-3)",
        },
        black: "var(--color-black)",
        gray: {
          DEFAULT: "var(--color-gray)",
          2: "var(--color-gray-2)",
          3: "var(--color-gray-3)",
          4: "var(--color-gray-4)",
          5: "var(--color-gray-5)",
          6: "var(--color-gray-6)",
          7: "var(--color-gray-7)",
          8: "var(--color-gray-8)",
          9: "var(--color-gray-9)",
          10: "var(--color-gray-10)",
          11: "var(--color-gray-11)",
          12: "var(--color-gray-12)",
          13: "var(--color-gray-13)",
          14: "var(--color-gray-14)",
          15: "var(--color-gray-15)",
          16: "var(--color-gray-16)",
          17: "var(--color-gray-17)",
          18: "var(--color-gray-18)",
          19: "var(--color-gray-19)",
          20: "var(--color-gray-20)",
          21: "var(--color-gray-21)",
          22: "var(--color-gray-22)",
          23: "var(--color-gray-23)",
          24: "var(--color-gray-24)",
          25: "var(--color-gray-25)",
          26: "var(--color-gray-26)",
          27: "var(--color-gray-27)",
        },
        red: {
          DEFAULT: "var(--color-red)",
          2: "var(--color-red-2)",
          3: "var(--color-red-3)",
          4: "var(--color-red-4)",
        },
        pink: "var(--color-pink)",
        blue: {
          DEFAULT: "var(--color-blue)",
          2: "var(--color-blue-2)",
          3: "var(--color-blue-3)",
          4: "var(--color-blue-4)",
        },
        green: {
          DEFAULT: "var(--color-green)",
          2: "var(--color-green-2)",
          3: "var(--color-green-3)",
          4: "var(--color-green-4)",
        },
        yellow: {
          DEFAULT: "var(--color-yellow)",
          2: "var(--color-yellow-2)",
          3: "var(--color-yellow-3)",
          4: "var(--color-yellow-4)",
        },
      },
    },
  },
};
