/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicAuthRouteImport } from './routes/_public/auth'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppPositionsRouteImport } from './routes/_app/positions'
import { Route as AppLanguagesRouteImport } from './routes/_app/languages'
import { Route as AppDepartmentsRouteImport } from './routes/_app/departments'
import { Route as AppCvsRouteImport } from './routes/_app/cvs'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppUsersUserIdIndexRouteImport } from './routes/_app/users/$userId.index'
import { Route as AppUsersUserIdSkillsRouteImport } from './routes/_app/users/$userId.skills'
import { Route as AppUsersUserIdProfileRouteImport } from './routes/_app/users/$userId.profile'
import { Route as AppUsersUserIdLanguagesRouteImport } from './routes/_app/users/$userId.languages'
import { Route as AppUsersUserIdCvsRouteImport } from './routes/_app/users/$userId.cvs'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPositionsRoute = AppPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLanguagesRoute = AppLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCvsRoute = AppCvsRouteImport.update({
  id: '/cvs',
  path: '/cvs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersUserIdIndexRoute = AppUsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersUserIdRoute,
} as any)
const AppUsersUserIdSkillsRoute = AppUsersUserIdSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppUsersUserIdRoute,
} as any)
const AppUsersUserIdProfileRoute = AppUsersUserIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppUsersUserIdRoute,
} as any)
const AppUsersUserIdLanguagesRoute = AppUsersUserIdLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => AppUsersUserIdRoute,
} as any)
const AppUsersUserIdCvsRoute = AppUsersUserIdCvsRouteImport.update({
  id: '/cvs',
  path: '/cvs',
  getParentRoute: () => AppUsersUserIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/cvs': typeof AppCvsRoute
  '/departments': typeof AppDepartmentsRoute
  '/languages': typeof AppLanguagesRoute
  '/positions': typeof AppPositionsRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/auth': typeof PublicAuthRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/users/$userId': typeof AppUsersUserIdRouteWithChildren
  '/users/$userId/cvs': typeof AppUsersUserIdCvsRoute
  '/users/$userId/languages': typeof AppUsersUserIdLanguagesRoute
  '/users/$userId/profile': typeof AppUsersUserIdProfileRoute
  '/users/$userId/skills': typeof AppUsersUserIdSkillsRoute
  '/users/$userId/': typeof AppUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/cvs': typeof AppCvsRoute
  '/departments': typeof AppDepartmentsRoute
  '/languages': typeof AppLanguagesRoute
  '/positions': typeof AppPositionsRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/auth': typeof PublicAuthRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/users/$userId/cvs': typeof AppUsersUserIdCvsRoute
  '/users/$userId/languages': typeof AppUsersUserIdLanguagesRoute
  '/users/$userId/profile': typeof AppUsersUserIdProfileRoute
  '/users/$userId/skills': typeof AppUsersUserIdSkillsRoute
  '/users/$userId': typeof AppUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_app/cvs': typeof AppCvsRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/languages': typeof AppLanguagesRoute
  '/_app/positions': typeof AppPositionsRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_public/auth': typeof PublicAuthRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/_app/': typeof AppIndexRoute
  '/_app/users/$userId': typeof AppUsersUserIdRouteWithChildren
  '/_app/users/$userId/cvs': typeof AppUsersUserIdCvsRoute
  '/_app/users/$userId/languages': typeof AppUsersUserIdLanguagesRoute
  '/_app/users/$userId/profile': typeof AppUsersUserIdProfileRoute
  '/_app/users/$userId/skills': typeof AppUsersUserIdSkillsRoute
  '/_app/users/$userId/': typeof AppUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cvs'
    | '/departments'
    | '/languages'
    | '/positions'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/users/$userId'
    | '/users/$userId/cvs'
    | '/users/$userId/languages'
    | '/users/$userId/profile'
    | '/users/$userId/skills'
    | '/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cvs'
    | '/departments'
    | '/languages'
    | '/positions'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/users/$userId/cvs'
    | '/users/$userId/languages'
    | '/users/$userId/profile'
    | '/users/$userId/skills'
    | '/users/$userId'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/cvs'
    | '/_app/departments'
    | '/_app/languages'
    | '/_app/positions'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/skills'
    | '/_public/auth'
    | '/_public/forgot-password'
    | '/_public/reset-password'
    | '/_public/verify-email'
    | '/_app/'
    | '/_app/users/$userId'
    | '/_app/users/$userId/cvs'
    | '/_app/users/$userId/languages'
    | '/_app/users/$userId/profile'
    | '/_app/users/$userId/skills'
    | '/_app/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/positions': {
      id: '/_app/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AppPositionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/languages': {
      id: '/_app/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof AppLanguagesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cvs': {
      id: '/_app/cvs'
      path: '/cvs'
      fullPath: '/cvs'
      preLoaderRoute: typeof AppCvsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users/$userId/': {
      id: '/_app/users/$userId/'
      path: '/'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof AppUsersUserIdIndexRouteImport
      parentRoute: typeof AppUsersUserIdRoute
    }
    '/_app/users/$userId/skills': {
      id: '/_app/users/$userId/skills'
      path: '/skills'
      fullPath: '/users/$userId/skills'
      preLoaderRoute: typeof AppUsersUserIdSkillsRouteImport
      parentRoute: typeof AppUsersUserIdRoute
    }
    '/_app/users/$userId/profile': {
      id: '/_app/users/$userId/profile'
      path: '/profile'
      fullPath: '/users/$userId/profile'
      preLoaderRoute: typeof AppUsersUserIdProfileRouteImport
      parentRoute: typeof AppUsersUserIdRoute
    }
    '/_app/users/$userId/languages': {
      id: '/_app/users/$userId/languages'
      path: '/languages'
      fullPath: '/users/$userId/languages'
      preLoaderRoute: typeof AppUsersUserIdLanguagesRouteImport
      parentRoute: typeof AppUsersUserIdRoute
    }
    '/_app/users/$userId/cvs': {
      id: '/_app/users/$userId/cvs'
      path: '/cvs'
      fullPath: '/users/$userId/cvs'
      preLoaderRoute: typeof AppUsersUserIdCvsRouteImport
      parentRoute: typeof AppUsersUserIdRoute
    }
  }
}

interface AppUsersUserIdRouteChildren {
  AppUsersUserIdCvsRoute: typeof AppUsersUserIdCvsRoute
  AppUsersUserIdLanguagesRoute: typeof AppUsersUserIdLanguagesRoute
  AppUsersUserIdProfileRoute: typeof AppUsersUserIdProfileRoute
  AppUsersUserIdSkillsRoute: typeof AppUsersUserIdSkillsRoute
  AppUsersUserIdIndexRoute: typeof AppUsersUserIdIndexRoute
}

const AppUsersUserIdRouteChildren: AppUsersUserIdRouteChildren = {
  AppUsersUserIdCvsRoute: AppUsersUserIdCvsRoute,
  AppUsersUserIdLanguagesRoute: AppUsersUserIdLanguagesRoute,
  AppUsersUserIdProfileRoute: AppUsersUserIdProfileRoute,
  AppUsersUserIdSkillsRoute: AppUsersUserIdSkillsRoute,
  AppUsersUserIdIndexRoute: AppUsersUserIdIndexRoute,
}

const AppUsersUserIdRouteWithChildren = AppUsersUserIdRoute._addFileChildren(
  AppUsersUserIdRouteChildren,
)

interface AppRouteRouteChildren {
  AppCvsRoute: typeof AppCvsRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppLanguagesRoute: typeof AppLanguagesRoute
  AppPositionsRoute: typeof AppPositionsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCvsRoute: AppCvsRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppLanguagesRoute: AppLanguagesRoute,
  AppPositionsRoute: AppPositionsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppIndexRoute: AppIndexRoute,
  AppUsersUserIdRoute: AppUsersUserIdRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthRoute: typeof PublicAuthRoute
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthRoute: PublicAuthRoute,
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
